# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: Lint
on: [pull_request]  # yamllint disable-line rule:truthy

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          # runs 'bundle install' and caches installed gems automatically:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop --format github
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
